/*

389. Find the Difference 

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        // Hash table for known size
        vector<int> map(26, 0);
        // Hash
        for(char c: s)  map[c - 'a']++;
        // Search and update
        for(char c: t) {
            if(--map[c-'a'] < 0)
                return c;
        }
        // Really should never reach here
        return '\0';
    }
};